name: Test And Deploy

on:
  pull_request:
    types: [ opened, edited, synchronize ]
  push:
    branches:
      - master
      - develop

jobs:
  laravel-tests:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.1'
    - uses: actions/checkout@v3
    
    - name: Run MySQL
      run: sudo systemctl start mysql.service
      
    - name: Cache composer dependencies
      uses: actions/cache@v2
      with:
        path: vendor
        key: composer-${{ hashFiles('composer.lock') }}
      
    - name: Run composer install
      run: |
          composer install -n --prefer-dist
          
    - name: Prepare Laravel Application
      run: |
          cp .env.example .env
          php artisan key:generate
      
    - name: Run Laravel Pint (code checker)
      run: ./vendor/bin/pint --test
      
    - name: Security checker
      run: php ./vendor/bin/security-checker security:check composer.lock
      
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
      
    - name: Cache npm dependencies
      uses: actions/cache@v1
      with:
          path: node_modules
          key: package-${{ hashFiles('package-lock.json') }}

    - name: Run NPM
      run: npm install && npm run build

    - name: Run migrate and seed database
      run: |
          mysql -uroot -proot -e "create database contact_plus"
          php artisan migrate:fresh --seed
    - name: Run tests
      run: ./vendor/bin/phpunit --testdox
      env:
          APP_ENV: testing

    - name: Upload artifacts
      uses: actions/upload-artifact@master
      if: failure()
      with:
          name: Logs
          path: ./storage/logs
